echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-25 and learning DevOps"
echo "Hello, Good morning!"
echo "i am learning git and github"
echo "good evening"
